name: Deploy-Android-TEST
on:
  push:
    branches:    
      - test
      
env:
  APP_CENTER_TOKEN: ${{ secrets.APPCENTER_TOKEN_TIME_MANAGER_TEST }}
  APP_NAME: ${{ 'Time-Manager-Android/ENV_TEST' }}
  TESTING_GROUP: ${{ 'ENV_TEST' }}
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/app-release.apk' }}
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build android
        run: npm run cd android && ./gradlew assembleRelease
      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: ${{ env.TESTING_GROUP }}
          file: ${{ env.UPLOAD_FILE }}
          notifyTesters: true
          debug: false
